# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/sbin/cmake

# The command to remove a file.
RM = /usr/sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/scripting_entity/Desktop/projects/Macro Nation"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/scripting_entity/Desktop/projects/Macro Nation"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/scripting_entity/Desktop/projects/Macro Nation/CMakeFiles" "/home/scripting_entity/Desktop/projects/Macro Nation//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/scripting_entity/Desktop/projects/Macro Nation/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named patterns_impl

# Build rule for target.
patterns_impl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 patterns_impl
.PHONY : patterns_impl

# fast build rule for target.
patterns_impl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/patterns_impl.dir/build.make CMakeFiles/patterns_impl.dir/build
.PHONY : patterns_impl/fast

#=============================================================================
# Target rules for targets named fields_impl

# Build rule for target.
fields_impl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fields_impl
.PHONY : fields_impl

# fast build rule for target.
fields_impl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fields_impl.dir/build.make CMakeFiles/fields_impl.dir/build
.PHONY : fields_impl/fast

#=============================================================================
# Target rules for targets named sub_macros

# Build rule for target.
sub_macros: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sub_macros
.PHONY : sub_macros

# fast build rule for target.
sub_macros/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sub_macros.dir/build.make CMakeFiles/sub_macros.dir/build
.PHONY : sub_macros/fast

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

application.o: application.cpp.o
.PHONY : application.o

# target to build an object file
application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/application.cpp.o
.PHONY : application.cpp.o

application.i: application.cpp.i
.PHONY : application.i

# target to preprocess a source file
application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/application.cpp.i
.PHONY : application.cpp.i

application.s: application.cpp.s
.PHONY : application.s

# target to generate assembly for a file
application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/application.cpp.s
.PHONY : application.cpp.s

core.o: core.cpp.o
.PHONY : core.o

# target to build an object file
core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/core.cpp.o
.PHONY : core.cpp.o

core.i: core.cpp.i
.PHONY : core.i

# target to preprocess a source file
core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/core.cpp.i
.PHONY : core.cpp.i

core.s: core.cpp.s
.PHONY : core.s

# target to generate assembly for a file
core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/core.cpp.s
.PHONY : core.cpp.s

fields_impl/pine_tree_forest.o: fields_impl/pine_tree_forest.cpp.o
.PHONY : fields_impl/pine_tree_forest.o

# target to build an object file
fields_impl/pine_tree_forest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fields_impl.dir/build.make CMakeFiles/fields_impl.dir/fields_impl/pine_tree_forest.cpp.o
.PHONY : fields_impl/pine_tree_forest.cpp.o

fields_impl/pine_tree_forest.i: fields_impl/pine_tree_forest.cpp.i
.PHONY : fields_impl/pine_tree_forest.i

# target to preprocess a source file
fields_impl/pine_tree_forest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fields_impl.dir/build.make CMakeFiles/fields_impl.dir/fields_impl/pine_tree_forest.cpp.i
.PHONY : fields_impl/pine_tree_forest.cpp.i

fields_impl/pine_tree_forest.s: fields_impl/pine_tree_forest.cpp.s
.PHONY : fields_impl/pine_tree_forest.s

# target to generate assembly for a file
fields_impl/pine_tree_forest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fields_impl.dir/build.make CMakeFiles/fields_impl.dir/fields_impl/pine_tree_forest.cpp.s
.PHONY : fields_impl/pine_tree_forest.cpp.s

imgui/backends/imgui_impl_glfw.o: imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui/backends/imgui_impl_glfw.o

# target to build an object file
imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui/backends/imgui_impl_glfw.cpp.o

imgui/backends/imgui_impl_glfw.i: imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui/backends/imgui_impl_glfw.cpp.i

imgui/backends/imgui_impl_glfw.s: imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui/backends/imgui_impl_glfw.cpp.s

imgui/backends/imgui_impl_opengl3.o: imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl3.o

# target to build an object file
imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.o

imgui/backends/imgui_impl_opengl3.i: imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.i

imgui/backends/imgui_impl_opengl3.s: imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

interface.o: interface.cpp.o
.PHONY : interface.o

# target to build an object file
interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/interface.cpp.o
.PHONY : interface.cpp.o

interface.i: interface.cpp.i
.PHONY : interface.i

# target to preprocess a source file
interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/interface.cpp.i
.PHONY : interface.cpp.i

interface.s: interface.cpp.s
.PHONY : interface.s

# target to generate assembly for a file
interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/interface.cpp.s
.PHONY : interface.cpp.s

patterns_impl/tidalwave.o: patterns_impl/tidalwave.cpp.o
.PHONY : patterns_impl/tidalwave.o

# target to build an object file
patterns_impl/tidalwave.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/patterns_impl.dir/build.make CMakeFiles/patterns_impl.dir/patterns_impl/tidalwave.cpp.o
.PHONY : patterns_impl/tidalwave.cpp.o

patterns_impl/tidalwave.i: patterns_impl/tidalwave.cpp.i
.PHONY : patterns_impl/tidalwave.i

# target to preprocess a source file
patterns_impl/tidalwave.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/patterns_impl.dir/build.make CMakeFiles/patterns_impl.dir/patterns_impl/tidalwave.cpp.i
.PHONY : patterns_impl/tidalwave.cpp.i

patterns_impl/tidalwave.s: patterns_impl/tidalwave.cpp.s
.PHONY : patterns_impl/tidalwave.s

# target to generate assembly for a file
patterns_impl/tidalwave.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/patterns_impl.dir/build.make CMakeFiles/patterns_impl.dir/patterns_impl/tidalwave.cpp.s
.PHONY : patterns_impl/tidalwave.cpp.s

sub_macros/mondo.o: sub_macros/mondo.cpp.o
.PHONY : sub_macros/mondo.o

# target to build an object file
sub_macros/mondo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sub_macros.dir/build.make CMakeFiles/sub_macros.dir/sub_macros/mondo.cpp.o
.PHONY : sub_macros/mondo.cpp.o

sub_macros/mondo.i: sub_macros/mondo.cpp.i
.PHONY : sub_macros/mondo.i

# target to preprocess a source file
sub_macros/mondo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sub_macros.dir/build.make CMakeFiles/sub_macros.dir/sub_macros/mondo.cpp.i
.PHONY : sub_macros/mondo.cpp.i

sub_macros/mondo.s: sub_macros/mondo.cpp.s
.PHONY : sub_macros/mondo.s

# target to generate assembly for a file
sub_macros/mondo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sub_macros.dir/build.make CMakeFiles/sub_macros.dir/sub_macros/mondo.cpp.s
.PHONY : sub_macros/mondo.cpp.s

sub_macros/positions.o: sub_macros/positions.cpp.o
.PHONY : sub_macros/positions.o

# target to build an object file
sub_macros/positions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sub_macros.dir/build.make CMakeFiles/sub_macros.dir/sub_macros/positions.cpp.o
.PHONY : sub_macros/positions.cpp.o

sub_macros/positions.i: sub_macros/positions.cpp.i
.PHONY : sub_macros/positions.i

# target to preprocess a source file
sub_macros/positions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sub_macros.dir/build.make CMakeFiles/sub_macros.dir/sub_macros/positions.cpp.i
.PHONY : sub_macros/positions.cpp.i

sub_macros/positions.s: sub_macros/positions.cpp.s
.PHONY : sub_macros/positions.s

# target to generate assembly for a file
sub_macros/positions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sub_macros.dir/build.make CMakeFiles/sub_macros.dir/sub_macros/positions.cpp.s
.PHONY : sub_macros/positions.cpp.s

sub_macros/red_cannon.o: sub_macros/red_cannon.cpp.o
.PHONY : sub_macros/red_cannon.o

# target to build an object file
sub_macros/red_cannon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sub_macros.dir/build.make CMakeFiles/sub_macros.dir/sub_macros/red_cannon.cpp.o
.PHONY : sub_macros/red_cannon.cpp.o

sub_macros/red_cannon.i: sub_macros/red_cannon.cpp.i
.PHONY : sub_macros/red_cannon.i

# target to preprocess a source file
sub_macros/red_cannon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sub_macros.dir/build.make CMakeFiles/sub_macros.dir/sub_macros/red_cannon.cpp.i
.PHONY : sub_macros/red_cannon.cpp.i

sub_macros/red_cannon.s: sub_macros/red_cannon.cpp.s
.PHONY : sub_macros/red_cannon.s

# target to generate assembly for a file
sub_macros/red_cannon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sub_macros.dir/build.make CMakeFiles/sub_macros.dir/sub_macros/red_cannon.cpp.s
.PHONY : sub_macros/red_cannon.cpp.s

theme_api.o: theme_api.cpp.o
.PHONY : theme_api.o

# target to build an object file
theme_api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/theme_api.cpp.o
.PHONY : theme_api.cpp.o

theme_api.i: theme_api.cpp.i
.PHONY : theme_api.i

# target to preprocess a source file
theme_api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/theme_api.cpp.i
.PHONY : theme_api.cpp.i

theme_api.s: theme_api.cpp.s
.PHONY : theme_api.s

# target to generate assembly for a file
theme_api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/theme_api.cpp.s
.PHONY : theme_api.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/utils.cpp.s
.PHONY : utils.cpp.s

walk.o: walk.cpp.o
.PHONY : walk.o

# target to build an object file
walk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/walk.cpp.o
.PHONY : walk.cpp.o

walk.i: walk.cpp.i
.PHONY : walk.i

# target to preprocess a source file
walk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/walk.cpp.i
.PHONY : walk.cpp.i

walk.s: walk.cpp.s
.PHONY : walk.s

# target to generate assembly for a file
walk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/walk.cpp.s
.PHONY : walk.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... app"
	@echo "... fields_impl"
	@echo "... patterns_impl"
	@echo "... sub_macros"
	@echo "... application.o"
	@echo "... application.i"
	@echo "... application.s"
	@echo "... core.o"
	@echo "... core.i"
	@echo "... core.s"
	@echo "... fields_impl/pine_tree_forest.o"
	@echo "... fields_impl/pine_tree_forest.i"
	@echo "... fields_impl/pine_tree_forest.s"
	@echo "... imgui/backends/imgui_impl_glfw.o"
	@echo "... imgui/backends/imgui_impl_glfw.i"
	@echo "... imgui/backends/imgui_impl_glfw.s"
	@echo "... imgui/backends/imgui_impl_opengl3.o"
	@echo "... imgui/backends/imgui_impl_opengl3.i"
	@echo "... imgui/backends/imgui_impl_opengl3.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... interface.o"
	@echo "... interface.i"
	@echo "... interface.s"
	@echo "... patterns_impl/tidalwave.o"
	@echo "... patterns_impl/tidalwave.i"
	@echo "... patterns_impl/tidalwave.s"
	@echo "... sub_macros/mondo.o"
	@echo "... sub_macros/mondo.i"
	@echo "... sub_macros/mondo.s"
	@echo "... sub_macros/positions.o"
	@echo "... sub_macros/positions.i"
	@echo "... sub_macros/positions.s"
	@echo "... sub_macros/red_cannon.o"
	@echo "... sub_macros/red_cannon.i"
	@echo "... sub_macros/red_cannon.s"
	@echo "... theme_api.o"
	@echo "... theme_api.i"
	@echo "... theme_api.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... walk.o"
	@echo "... walk.i"
	@echo "... walk.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

